export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES';
export const LOAD_SLIDER_ARTICLES = 'LOAD_SLIDER_ARTICLES';
export const LOAD_FROM_TO_ARTICLES = 'LOAD_FROM_TO_ARTICLES';
export const SELECT_ARTICLE = 'SELECT_ARTICLE';
export const UPDATE_ALL_ARTICLES = 'UPDATE_ALL_ARTICLES';
export const CLOSE_ARTICLE = 'CLOSE_ARTICLE';

export const LOAD_MENU = 'LOAD_MENU';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const CHANGE_DESCRIPTION_MENU = 'CHANGE_DESCRIPTION_MENU';

export const LOAD_CONTACTUS = 'LOAD_CONTACTUS';

export const LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES';
export const CHANGE_SELECTED_CATEGORIES = 'CHANGE_SELECTED_CATEGORIES';
export const TOGGLE_MENU_CATEGORIES = 'TOGGLE_MENU_CATEGORIES';
export const CLOSE_MENU_CATEGORIES = 'CLOSE_MENU_CATEGORIES';
export const HIDDEN_MENU_CATEGORIES = 'HIDDEN_MENU_CATEGORIES';
export const VISIBLE_MENU_CATEGORIES = 'VISIBLE_MENU_CATEGORIES';

export const LOAD_ALL_EMPLOEES = 'LOAD_ALL_EMPLOEES';

export const CURSOR_ENTER = 'CURSOR_ENTER';
export const CURSOR_LEAVE  = 'CURSOR_LEAVE';

export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';
