export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES';

export const LOAD_FROM_TO_ARTICLES = 'LOAD_FROM_TO_ARTICLES';

export const LOAD_ARTICLES_CAROUSEL = 'LOAD_ARTICLES_CAROUSEL';

export const LOAD_MENU = 'LOAD_MENU';

export const LOAD_CONTACTUS = 'LOAD_CONTACTUS';

export const LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES';

export const CHANGE_SELECTED_CATEGORIES = 'CHANGE_SELECTED_CATEGORIES';